version: "3.9"

services:
  #---------------PostgreSQl Database-----------------

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  #------------FASTApi Backend--------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/investdb
      DATABASE_URL_SYNC: postgresql://postgres:postgres@db:5432/investdb
      DEBUG: "true"
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      NEWS_API_KEY: ${NEWS_API_KEY}
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
      CORS_ORIGINS: '["http://localhost:5173","http://localhost:3000"]'
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_data
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for DB...' &&
        sleep 2 &&
        python -m scripts.seed &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  chroma_data:
    